export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  googleApiKey: process.env.GOOGLE_API_KEY ?? "AIzaSyDlzBesSH_l_Xj7ivU3YEzTjoCHvu3qc5Q",
  serpApiKey: process.env.SERPAPI_KEY ?? "d0c982379954fe11a405499ed5747a5d19f669e071643986bc79c74e7ce87a54",
  plaidClientId: process.env.PLAID_CLIENT_ID ?? "",
  plaidSecret: process.env.PLAID_SECRET ?? "",
  plaidEnv: process.env.PLAID_ENV ?? "sandbox",
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID ?? "",
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN ?? "",
  twilioWhatsappNumber: process.env.TWILIO_WHATSAPP_NUMBER ?? "",
  // WhatsApp Cloud API (360Dialog / Meta)
  whatsappPhoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID ?? "",
  whatsappAccessToken: process.env.WHATSAPP_ACCESS_TOKEN ?? "",
  whatsappWebhookToken: process.env.WHATSAPP_WEBHOOK_TOKEN ?? "",
  viteAppUrl: process.env.VITE_APP_URL ?? "",
};
